;;; majutsu-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from majutsu.el

(defalias 'majutsu 'majutsu-log "\
Begin using Majutsu.

This alias for `majutsu-log' exists for better discoverability.

Instead of invoking this alias for `majutsu-log' using
\"M-x majutsu RET\", you should bind a key to `majutsu-log'.")
(autoload 'majutsu-dispatch "majutsu" "\
Top-level Majutsu command dispatcher.

(fn)" t)


;;; Generated autoloads from majutsu-absorb.el

(autoload 'majutsu-absorb-execute "majutsu-absorb" "\
Execute jj absorb with ARGS from the transient.

(fn ARGS)" t)
(autoload 'majutsu-absorb "majutsu-absorb" "\
Transient for jj absorb operations.

(fn)" t)
(register-definition-prefixes "majutsu-absorb" '("majutsu-absorb-"))


;;; Generated autoloads from majutsu-annotate.el

(autoload 'majutsu-annotate-addition "majutsu-annotate" "\
Annotate the current file showing when each line was added.
With prefix argument, prompt for REVISION.

If already annotating with the same type, and point is on a chunk
that has a parent revision, then recursively annotate the parent.

(fn &optional REVISION)" t)
(register-definition-prefixes "majutsu-annotate" '("majutsu-annotate-"))


;;; Generated autoloads from majutsu-base.el

(register-definition-prefixes "majutsu-base" '("majutsu-"))


;;; Generated autoloads from majutsu-bookmark.el

(autoload 'majutsu-bookmark-create "majutsu-bookmark" "\
Create a new bookmark." t)
(autoload 'majutsu-bookmark-delete "majutsu-bookmark" "\
Delete a bookmark and propagate on next push." t)
(autoload 'majutsu-bookmark-forget "majutsu-bookmark" "\
Forget a bookmark (local only, no deletion propagation)." t)
(autoload 'majutsu-bookmark-track "majutsu-bookmark" "\
Track remote bookmark(s)." t)
(autoload 'majutsu-bookmark-list "majutsu-bookmark" "\
List bookmarks in a dedicated buffer.
With prefix ALL, include remote bookmarks.

(fn &optional ALL)" t)
(autoload 'majutsu-read-bookmarks "majutsu-bookmark" "\
Return interactive arguments for bookmark move commands.

(fn PROMPT &optional INIT-INPUT HISTORY)")
(autoload 'majutsu-bookmark-move "majutsu-bookmark" "\
Move bookmark bookmark(s) NAMES to COMMIT.
With optional ALLOW-BACKWARDS, pass `--allow-backwards' to jj.

(fn NAMES COMMIT &optional ALLOW-BACKWARDS)" t)
(autoload 'majutsu-bookmark-move-allow-backwards "majutsu-bookmark" "\
Move bookmark(s) NAMES to COMMIT allowing backwards moves.

(fn NAMES COMMIT)" t)
(autoload 'majutsu-bookmark-rename "majutsu-bookmark" "\
Rename bookmark OLD to NEW.

(fn OLD NEW)" t)
(autoload 'majutsu-bookmark-set "majutsu-bookmark" "\
Create or update bookmark NAME to point to COMMIT.

(fn NAME COMMIT)" t)
(autoload 'majutsu-bookmark-untrack "majutsu-bookmark" "\
Stop tracking remote bookmark(s).

BOOKMARKS are bookmark name patterns (glob/exact/regex/substring).
REMOTES are remote name patterns passed via repeated `--remote`.

(fn BOOKMARKS &optional REMOTES)" t)
(register-definition-prefixes "majutsu-bookmark" '("majutsu-"))


;;; Generated autoloads from majutsu-color-words.el

(register-definition-prefixes "majutsu-color-words" '("majutsu-color-words-"))


;;; Generated autoloads from majutsu-commit.el

(autoload 'majutsu-commit "majutsu-commit" "\
Create a commit using Emacs as the editor." t)
(autoload 'majutsu-describe "majutsu-commit" "\
Update the description for the commit at point.
With prefix ARG, add --ignore-immutable.

(fn &optional ARG)" t)


;;; Generated autoloads from majutsu-config.el

(register-definition-prefixes "majutsu-config" '("majutsu-"))


;;; Generated autoloads from majutsu-conflict.el

(autoload 'majutsu-conflict-refine "majutsu-conflict" "\
Add word-level refinement to conflict regions.
Call this command to highlight fine-grained differences within conflicts." t)
(autoload 'majutsu-conflict-mode "majutsu-conflict" "\
Minor mode for jj conflict markers.

Provides highlighting and navigation for conflict regions.

This is a minor mode.  If called interactively, toggle the
`Majutsu-Conflict mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `majutsu-conflict-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'majutsu-conflict-ensure-mode "majutsu-conflict" "\
Enable conflict mode based on marker style in the buffer.

Prefer `majutsu-conflict-mode' for JJ-style conflicts.  If only Git-style
markers are present, enable `smerge-mode'.")
(autoload 'majutsu-conflict-check-enable "majutsu-conflict" "\
Enable conflict mode if buffer has conflict markers.")
(register-definition-prefixes "majutsu-conflict" '("majutsu-conflict-"))


;;; Generated autoloads from majutsu-core.el

(register-definition-prefixes "majutsu-core" '("majutsu-"))


;;; Generated autoloads from majutsu-diff.el

(autoload 'majutsu-diff-visit-file "majutsu-diff" "\
From a diff, visit the appropriate version of the file at point.

If point is on an added or context line, visit the new/right side.
If point is on a removed line, visit the old/left side.

For diffs of the working copy (@), this visits the actual file in
the workspace.  For diffs of committed changes, this visits the
blob from the appropriate revision.

With prefix argument FORCE-WORKSPACE, always visit the workspace file
regardless of what the diff is about.

(fn &optional FORCE-WORKSPACE)" t)
(autoload 'majutsu-diff-visit-workspace-file "majutsu-diff" "\
From a diff, visit the workspace version of the file at point.
Always visits the actual file in the working tree, regardless of
what the diff is about." t)
(autoload 'majutsu-diff-dwim "majutsu-diff" "\
Show changes for the thing at point.

(fn &optional ARGS RANGE FILESETS)" t)
(autoload 'majutsu-diff-revset "majutsu-diff" "\
Show changes for a REVSET.

REVSET is passed to jj diff using `--revisions='.

(fn REVSET &optional ARGS RANGE FILESETS)" t)
(autoload 'majutsu-diff "majutsu-diff" "\
Internal transient for jj diff.

(fn)" t)
(register-definition-prefixes "majutsu-diff" '("majutsu-"))


;;; Generated autoloads from majutsu-duplicate.el

(autoload 'majutsu-duplicate-dwim "majutsu-duplicate" "\
Duplicate the changeset at point.
With prefix ARG, open the duplicate transient." t)
(register-definition-prefixes "majutsu-duplicate" '("majutsu-duplicate-"))


;;; Generated autoloads from majutsu-ediff.el

(autoload 'majutsu-ediff-compare "majutsu-ediff" "\
Compare FILE between FROM and TO revisions using Ediff.
If FILE is nil, prompt for one.

(fn FROM TO &optional FILE)" t)
(autoload 'majutsu-ediff-show-revision "majutsu-ediff" "\
Show changes in REV using Ediff (parent vs rev).
If FILE is nil, prompt for one.

(fn REV &optional FILE)" t)
(autoload 'majutsu-ediff-dwim "majutsu-ediff" "\
Context-aware Ediff based on current section." t)
(autoload 'majutsu-ediff-edit "majutsu-ediff" "\
Edit one changed file with two-sided Ediff via jj diffedit.
ARGS are transient arguments.

(fn ARGS)" t)
(autoload 'majutsu-ediff-resolve "majutsu-ediff" "\
Resolve FILE conflicts using `jj resolve' with Emacs as merge editor.
If FILE is nil, DWIM selects from conflicted files at point revision (commit
section) or the working copy.

(fn &optional FILE)" t)
(autoload 'majutsu-ediff-resolve-with-conflict "majutsu-ediff" "\
Resolve conflicts using `majutsu-conflict-mode'.
When resolving a non-working-copy revision, open the matching blob buffer
at that revision before enabling conflict mode." t)
(autoload 'majutsu-ediff-diffedit-file "majutsu-ediff" "\
Compare one file from LEFT and RIGHT using Ediff.
This is called by jj diffedit when using Emacs as the diff editor.
Blocks until user finishes editing and quits Ediff.

(fn LEFT RIGHT)" t)
(autoload 'majutsu-ediff-merge-files "majutsu-ediff" "\
Resolve a 3-way merge with Ediff and write result to OUTPUT.
Called by `jj resolve` merge editor command via emacsclient.

(fn LEFT BASE RIGHT OUTPUT &optional MARKER-LENGTH)" t)
(autoload 'majutsu-ediff "majutsu-ediff" "\
Show differences using Ediff.

(fn)" t)
(register-definition-prefixes "majutsu-ediff" '("majutsu-ediff-"))


;;; Generated autoloads from majutsu-edit.el

(autoload 'majutsu-edit-changeset "majutsu-edit" "\
Edit commit at point.

With prefix ARG, pass --ignore-immutable.
When called from a blob buffer, also visit the workspace file.

(fn &optional ARG)" t)
(register-definition-prefixes "majutsu-edit" '("majutsu-"))


;;; Generated autoloads from majutsu-evil.el

(autoload 'majutsu-evil-setup "majutsu-evil" "\
Install Majutsu's native Evil integration.
Safe to call multiple times.  Set
`majutsu-evil-enable-integration' to nil to skip automatic setup." t)
(register-definition-prefixes "majutsu-evil" '("majutsu-"))


;;; Generated autoloads from majutsu-file.el

(autoload 'majutsu-find-file "majutsu-file" "\
View PATH from REVSET in a blob buffer.

(fn REVSET PATH)" t)
(autoload 'majutsu-find-file-at-point "majutsu-file" "\
View file at point from the relevant revision." t)
(register-definition-prefixes "majutsu-file" '("majutsu-"))


;;; Generated autoloads from majutsu-git.el

(autoload 'majutsu-git-push "majutsu-git" "\
Push to git remote with ARGS.

(fn ARGS)" t)
 (autoload 'majutsu-git-fetch "majutsu-git" nil t)
(autoload 'majutsu-git-transient "majutsu-git" "\
Top-level transient for jj git operations.

(fn)" t)
 (autoload 'majutsu-git-fetch-transient "majutsu-git" nil t)
(register-definition-prefixes "majutsu-git" '("majutsu-git-"))


;;; Generated autoloads from majutsu-interactive.el

(register-definition-prefixes "majutsu-interactive" '("majutsu-interactive-"))


;;; Generated autoloads from majutsu-jj.el

(register-definition-prefixes "majutsu-jj" '("majutsu-"))


;;; Generated autoloads from majutsu-jjdescription.el

(register-definition-prefixes "majutsu-jjdescription" '("global-majutsu-jjdescription-mode" "majutsu-jjdescription-"))


;;; Generated autoloads from majutsu-log.el

(autoload 'majutsu-goto-next-changeset "majutsu-log" "\
Navigate to the next changeset in the log." t)
(autoload 'majutsu-goto-prev-changeset "majutsu-log" "\
Navigate to the previous changeset in the log." t)
(autoload 'majutsu-log-refresh "majutsu-log" "\
Refresh a majutsu log buffer for the current repository.
When called outside a log buffer, try to refresh an existing log
buffer for the same repository.  If none exists and the command
is invoked interactively, signal a user error instead of
mutating the wrong buffer." t)
(autoload 'majutsu-log "majutsu-log" "\
Open the majutsu log buffer.

If the current directory isn't located within a jj repository, then
prompt for a directory.  If that directory isn't a repository either,
offer to create one using `jj git init`.

(fn &optional DIRECTORY)" t)
(autoload 'majutsu-log-transient "majutsu-log" "\
Transient interface for adjusting jj log options.

(fn)" t)
(register-definition-prefixes "majutsu-log" '("majutsu-"))


;;; Generated autoloads from majutsu-mode.el

(register-definition-prefixes "majutsu-mode" '("majutsu-"))


;;; Generated autoloads from majutsu-new.el

(autoload 'majutsu-new-dwim "majutsu-new" "\
Create a new changeset.
Without prefix ARG, use the changeset at point (or `@` when unavailable).
With prefix ARG, open the new transient for interactive selection.

(fn ARG)" t)
(autoload 'majutsu-new-with-after "majutsu-new" "\
Create a new changeset with the commit at point as --after." t)
(autoload 'majutsu-new-with-before "majutsu-new" "\
Create a new changeset with the commit at point as --before." t)
(autoload 'majutsu-new-execute "majutsu-new" "\
Execute jj new using the current transient selections.

(fn ARGS)" t)
(register-definition-prefixes "majutsu-new" '("majutsu-new-"))


;;; Generated autoloads from majutsu-op.el

(autoload 'majutsu-undo "majutsu-op" "\
Undo the last change." t)
(autoload 'majutsu-redo "majutsu-op" "\
Redo the last undone change." t)
(register-definition-prefixes "majutsu-op" '("majutsu-"))


;;; Generated autoloads from majutsu-process.el

(register-definition-prefixes "majutsu-process" '("majutsu-"))


;;; Generated autoloads from majutsu-rebase.el

(autoload 'majutsu-rebase-execute "majutsu-rebase" "\
Execute rebase with selected source and destinations.
ARGS are passed from the transient.

(fn ARGS)" t)
(register-definition-prefixes "majutsu-rebase" '("majutsu-rebase-"))


;;; Generated autoloads from majutsu-restore.el

(autoload 'majutsu-abandon "majutsu-restore" "\
Abandon the changeset at point or in region." t)
(autoload 'majutsu-restore-dwim "majutsu-restore" "\
Restore working copy from parent (discard all changes).
In diff buffer on a file section, restore only that file." t)
(register-definition-prefixes "majutsu-restore" '("majutsu-restore-"))


;;; Generated autoloads from majutsu-revert.el

(autoload 'majutsu-revert-execute "majutsu-revert" "\
Execute jj revert with ARGS from the transient.

(fn ARGS)" t)
(autoload 'majutsu-revert "majutsu-revert" "\
Transient for jj revert operations.

(fn)" t)
(register-definition-prefixes "majutsu-revert" '("majutsu-revert-"))


;;; Generated autoloads from majutsu-selection.el

(register-definition-prefixes "majutsu-selection" '("majutsu-selection-"))


;;; Generated autoloads from majutsu-sparse.el

(autoload 'majutsu-sparse-set "majutsu-sparse" "\
Set sparse patterns to PATTERNS.
With CLEAR non-nil, clear existing patterns first.
PATTERNS can be a single string or list of strings.

(fn PATTERNS &optional CLEAR)" t)
(autoload 'majutsu-sparse-set-clear "majutsu-sparse" "\
Clear all patterns and set to PATTERNS.
This is equivalent to `jj sparse set --clear --add <patterns>'.

(fn PATTERNS)" t)
(autoload 'majutsu-sparse-add "majutsu-sparse" "\
Add PATTERNS to current sparse patterns.
PATTERNS can be a single string or list of strings.

(fn PATTERNS)" t)
(autoload 'majutsu-sparse-remove "majutsu-sparse" "\
Remove PATTERNS from current sparse patterns.
PATTERNS can be a single string or list of strings.

(fn PATTERNS)" t)
(autoload 'majutsu-sparse-reset "majutsu-sparse" "\
Reset sparse patterns to include all files.
This is equivalent to `jj sparse reset'." t)
(autoload 'majutsu-sparse-edit "majutsu-sparse" "\
Edit sparse patterns in an editor.
This opens your configured editor with the current patterns." t)
(autoload 'majutsu-sparse-list "majutsu-sparse" "\
List current sparse patterns in a dedicated buffer." t)
(autoload 'majutsu-sparse "majutsu-sparse" nil t)
(register-definition-prefixes "majutsu-sparse" '("majutsu-"))


;;; Generated autoloads from majutsu-split.el

(register-definition-prefixes "majutsu-split" '("majutsu-split-"))


;;; Generated autoloads from majutsu-squash.el

(register-definition-prefixes "majutsu-squash" '("majutsu-squash-"))


;;; Generated autoloads from majutsu-tag.el

(autoload 'majutsu-tag-list "majutsu-tag" "\
List tags in a dedicated buffer.
With prefix ALL-REMOTES, include remote tags.

(fn &optional ALL-REMOTES)" t)
(autoload 'majutsu-tag-set "majutsu-tag" "\
Create or update tag NAMES to point to REVISION.
When ALLOW-MOVE is non-nil, pass `--allow-move'.

(fn NAMES REVISION &optional ALLOW-MOVE)" t)
(autoload 'majutsu-tag-delete "majutsu-tag" "\
Delete tag NAMES.
NAMES are passed as jj string patterns.

(fn NAMES)" t)
(autoload 'majutsu-tag-move "majutsu-tag" "\
Move existing tag NAMES to REVISION.
This is a convenience wrapper around `jj tag set --allow-move'.

(fn NAMES REVISION)" t)
(register-definition-prefixes "majutsu-tag" '("majutsu-"))


;;; Generated autoloads from majutsu-template.el

(autoload 'majutsu-template-defun "majutsu-template" "\
Define a majutsu template helper NAME with ARGS, SIGNATURE and BODY.
Generates `majutsu-template-NAME' and registers it for template DSL usage.

(fn NAME ARGS SIGNATURE &rest BODY)" nil t)
(function-put 'majutsu-template-defun 'lisp-indent-function 'defun)
(autoload 'majutsu-template-compile "majutsu-template" "\
Public entry point: compile FORM into a jj template string.
Optional SELF-TYPE overrides `majutsu-template-default-self-type'.

(fn FORM &optional SELF-TYPE)")
(autoload 'majutsu-tpl "majutsu-template" "\
Expand and compile FORM to a jj template string.
Vector literals are compiled at macro-expansion time IF SELF-TYPE is provided
as a constant.

If SELF-TYPE is not provided, compilation is deferred to runtime to respect
dynamic bindings of `majutsu-template-default-self-type'.

(fn FORM &optional SELF-TYPE)" nil t)
(register-definition-prefixes "majutsu-template" '("majutsu-template-"))


;;; Generated autoloads from majutsu-workspace.el

(autoload 'majutsu-insert-workspaces "majutsu-workspace" "\
Insert a Workspaces section.
When there is only one workspace, nothing is inserted unless called
from `majutsu-workspace-mode'.")
(autoload 'majutsu-workspace-visit "majutsu-workspace" "\
Visit workspace at point.

If called with DIRECTORY, visit that directory. Otherwise, try to locate the
workspace root automatically; if not found, prompt for it.

(fn &optional DIRECTORY)" t)
(autoload 'majutsu-workspace-list "majutsu-workspace" "\
Show workspaces in a dedicated buffer." t)
(autoload 'majutsu-workspace-root "majutsu-workspace" "\
Show and copy the current workspace root directory." t)
(autoload 'majutsu-workspace-update-stale "majutsu-workspace" "\
Update the current workspace if it has become stale." t)
(autoload 'majutsu-workspace-rename "majutsu-workspace" "\
Rename WORKSPACE to NEW-NAME.

Note that Jujutsu renames the workspace associated with the current
working directory, so this command may prompt for the workspace root
directory.

(fn WORKSPACE NEW-NAME)" t)
(autoload 'majutsu-workspace-forget "majutsu-workspace" "\
Forget workspaces NAMES.

This stops tracking the workspaces' working-copy commits in the repo. The
workspace directories are not touched on disk.

(fn NAMES)" t)
(autoload 'majutsu-workspace-add "majutsu-workspace" "\
Add a workspace.

DESTINATION is where to create the new workspace.
Optional NAME, REVISION (revset), and SPARSE-PATTERNS correspond to
  `jj workspace add` options.

(fn DESTINATION &optional NAME REVISION SPARSE-PATTERNS)" t)
(register-definition-prefixes "majutsu-workspace" '("majutsu-workspace-"))

;;; End of scraped data

(provide 'majutsu-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; majutsu-autoloads.el ends here
